defaults:
  source_branch: staging
  target_branch: main
  merge_method: squash

projects:
  - repository: Hikari-Tsai/twitch-bot
  - repository: Hikari-Tsai/dc-manager
  - repository: Hikari-Tsai/code-portfolio
  - repository: Hikari-Tsai/JS_Inflator
